# Generated by Django 3.1.7 on 2021-03-09 08:43

from django.db import migrations, models
import django.db.models.deletion
import fontawesome_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pruduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='images')),
                ('short_text', models.TextField(verbose_name='Short Text')),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Eski narx')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Xozirgi narx')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Rating')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Qushilgan sana')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='myshop.category', verbose_name='Katalog')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.pruduct', verbose_name='Tavar')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Jami summa')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Jami soni')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.pruduct', verbose_name='Tavar')),
            ],
            options={
                'verbose_name': 'Savatchadagi tavar',
                'verbose_name_plural': 'Savatchadagi tavarlar',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Umumiy summa')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy soni')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Ochilgan sanasi')),
                ('products', models.ManyToManyField(to='myshop.CartProduct')),
            ],
            options={
                'verbose_name': 'Savatcha',
                'verbose_name_plural': 'Savatchalar',
            },
        ),
    ]
