# Generated by Django 3.1.7 on 2021-03-10 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruduct',
            name='category',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myshop.category', verbose_name='SubCategorylar')),
            ],
        ),
        migrations.AddField(
            model_name='pruduct',
            name='subCategory',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='myshop.subcategory', verbose_name='Katalog'),
            preserve_default=False,
        ),
    ]
