# Generated by Django 3.1.7 on 2021-03-14 06:20

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('myshop', '0003_auto_20210314_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruduct',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
