# Generated by Django 3.1.7 on 2021-03-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_pruduct_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruduct',
            name='aaaa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
