# Generated by Django 3.1.7 on 2021-03-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_ranglar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruduct',
            name='aaaa',
        ),
    ]
