# Generated by Django 3.1.7 on 2021-03-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_remove_pruduct_aaaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruduct',
            name='rang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myshop.ranglar'),
        ),
    ]
