# Generated by Django 3.1.7 on 2021-03-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_auto_20210320_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruduct',
            name='old_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Eski narxi'),
        ),
        migrations.AlterField(
            model_name='pruduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Soni'),
        ),
    ]
