# Generated by Django 3.1.7 on 2021-04-02 08:43

from django.db import migrations, models
import django.db.models.deletion
import myshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_auto_20210321_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to=myshop.models.image_folder),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myshop.pruduct', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='pruduct',
            name='image',
            field=models.ImageField(upload_to=myshop.models.image_folder),
        ),
    ]
