# Generated by Django 3.1.7 on 2021-04-03 15:22

from django.db import migrations, models
import myshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_auto_20210403_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to=myshop.models.image_folder_blog, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='vaqt',
            field=models.DateField(auto_now_add=True, verbose_name='Vaqt'),
        ),
    ]
