# Generated by Django 3.1.7 on 2021-04-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0017_auto_20210403_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
    ]
