# Generated by Django 3.1.7 on 2021-04-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0018_remove_blog_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ['-id']},
        ),
    ]
