# Generated by Django 3.1.7 on 2021-04-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0020_pruduct_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
            ],
        ),
        migrations.RemoveField(
            model_name='pruduct',
            name='language',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='myshop.basiccategory', verbose_name='Categorylar'),
        ),
    ]
