# Generated by Django 3.1.7 on 2021-04-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0021_auto_20210408_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='pruduct',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', 'uz'), ('en', 'en')], max_length=20),
        ),
        migrations.DeleteModel(
            name='BasicCategory',
        ),
    ]
