# Generated by Django 3.1.7 on 2021-04-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0023_fact_facttranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name="Qo'shildi")),
                ('updated_date', models.DateField(auto_now=True, verbose_name="O'zgartirildi")),
                ('paid', models.BooleanField(verbose_name="To'landi")),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.pruduct')),
            ],
            options={
                'verbose_name': 'Buyurtma tavarlar',
                'verbose_name_plural': 'Buyurtma tavarlari',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.province', verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.province', verbose_name='Tuman'),
        ),
    ]
