# Generated by Django 3.1.7 on 2021-04-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0029_districts_districtstranslation_provinces_provincestranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.districts', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.provinces', verbose_name='Viloyat'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
