# Generated by Django 3.1.7 on 2021-04-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0030_auto_20210419_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
