# Generated by Django 3.1.7 on 2021-04-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0033_auto_20210419_0247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='pruduct',
            name='language',
        ),
    ]
