# Generated by Django 3.1.7 on 2021-04-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0035_maqolalar_maqolalartranslation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maqolalartranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='maqolalartranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='MaqolaLar',
        ),
        migrations.DeleteModel(
            name='MaqolaLarTranslation',
        ),
    ]
