# Generated by Django 3.1.7 on 2021-04-19 00:31

from django.db import migrations, models
import myshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0036_auto_20210419_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloglar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=myshop.models.image_folder_blog, verbose_name='Image')),
                ('vaqt', models.DateField(auto_now_add=True, verbose_name='Vaqt')),
            ],
        ),
    ]
