# Generated by Django 3.1.7 on 2021-04-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0041_bora_boratranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bloglar',
        ),
        migrations.AlterUniqueTogether(
            name='boratranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='boratranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='malmotlartranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='malmotlartranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Bora',
        ),
        migrations.DeleteModel(
            name='BoraTranslation',
        ),
        migrations.DeleteModel(
            name='Malmotlar',
        ),
        migrations.DeleteModel(
            name='MalmotlarTranslation',
        ),
    ]
