# Generated by Django 3.1.7 on 2021-04-19 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0043_yangiliklar_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'ordering': ['-id']},
        ),
    ]
