# Generated by Django 3.1.7 on 2021-04-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0045_auto_20210419_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorys',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='categorystranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': "Bo'lim Translation"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Tavar', 'verbose_name_plural': 'Tavarlar'},
        ),
        migrations.AlterModelOptions(
            name='producttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Tavar Translation'},
        ),
        migrations.AlterModelOptions(
            name='rang',
            options={'verbose_name': 'Rang', 'verbose_name_plural': 'Ranglar'},
        ),
        migrations.AlterModelOptions(
            name='rangtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Rang Translation'},
        ),
        migrations.AlterModelOptions(
            name='subcategorys',
            options={'verbose_name': "Qism bo'lim", 'verbose_name_plural': "Qism bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='subcategorystranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': "Qism bo'lim Translation"},
        ),
    ]
