# Generated by Django 3.1.7 on 2021-04-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0046_auto_20210419_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rang',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategorys',
            name='slug',
        ),
        migrations.AddField(
            model_name='categorystranslation',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='rangtranslation',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='subcategorystranslation',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
