# Generated by Django 3.1.7 on 2021-04-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0047_auto_20210419_1157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorystranslation',
            unique_together={('language_code', 'slug'), ('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('language_code', 'slug'), ('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='rangtranslation',
            unique_together={('language_code', 'slug'), ('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategorystranslation',
            unique_together={('language_code', 'slug'), ('language_code', 'master')},
        ),
    ]
