# Generated by Django 3.1.7 on 2021-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0052_cartproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproducts',
            options={'ordering': ['-id'], 'verbose_name': 'Savat tavar new'},
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Umumiy summa')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Umumiy soni')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Ochilgan sanasi')),
                ('products', models.ManyToManyField(to='myshop.CartProducts')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar new',
            },
        ),
    ]
