# Generated by Django 3.1.7 on 2021-05-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0053_auto_20210508_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproducts',
            options={'ordering': ['-id'], 'verbose_name': 'Savat tavar new', 'verbose_name_plural': 'Savat tavarlar new'},
        ),
        migrations.AlterModelOptions(
            name='carts',
            options={'verbose_name': 'Savat new', 'verbose_name_plural': 'Savatlar new'},
        ),
    ]
