# Generated by Django 3.1.7 on 2021-05-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0054_auto_20210508_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
