# Generated by Django 3.1.7 on 2021-05-08 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0055_auto_20210508_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=45, verbose_name='Email')),
                ('mahalla', models.CharField(max_length=100, verbose_name='Mahalla')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name="Qo'shildi")),
                ('updated_date', models.DateField(auto_now=True, verbose_name="O'zgartirildi")),
                ('paid', models.BooleanField(blank=True, null=True, verbose_name="To'landi")),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.districts', verbose_name='Tuman')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.provinces', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Buyurtma new',
                'verbose_name_plural': 'Buyurtmalar new',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitm', to='myshop.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.product')),
            ],
            options={
                'verbose_name': 'Buyurtma tavarlar new',
                'verbose_name_plural': 'Buyurtma tavarlari new',
            },
        ),
    ]
