# Generated by Django 3.1.7 on 2021-05-09 06:32

from django.db import migrations, models
import myshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0057_banner_bannertranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to=myshop.models.image_folder),
        ),
        migrations.AlterField(
            model_name='bannertranslation',
            name='chegirma',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bannertranslation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
