# Generated by Django 3.1.7 on 2021-07-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0058_auto_20210509_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Tavar', 'verbose_name_plural': 'Tavarlar'},
        ),
    ]
