# Generated by Django 3.2.8 on 2021-10-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0059_auto_20210731_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bannertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'banner Translation'},
        ),
        migrations.AlterModelOptions(
            name='cartproducts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorys',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorystranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'categorys Translation'},
        ),
        migrations.AlterModelOptions(
            name='districts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='districtstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'districts Translation'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='provinces',
            options={},
        ),
        migrations.AlterModelOptions(
            name='provincestranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'provinces Translation'},
        ),
        migrations.AlterModelOptions(
            name='subcategorys',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subcategorystranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'sub categorys Translation'},
        ),
    ]
